##bcl2human='MAHAGRTGYDNREIVMKYIHYKLSQRGYEWDAGDVGAAPPGAAPAPGIFSSQPGHTPHPAASRDPVARTSPLQTPAAPGAAAGPALSPVPPVVHLTLRQAGDDFSRRYRRDFAEMSSQLHLTPFTARGRFATVVEELFRDGVNWGRIVAFFEFGGVMCVESVNREMSPLVDNIALWMTEYLNRHLHTWIQDNGGWDAFVELYGPSMRPLFDFSWLSLKTLLSLALVGACITLGAYLGHK'
##bcl2gorilla='MAHAGRTGYDNREIVMKYIHYKLSQRGYEWDAGDVGAVPPGAAPAPGIFSSQPGHTPHPAASRDRVARTSPLQTPAAPGAAAGPALSPVPPVVHLTLRQAGDDFSRRYRRDFAEMSSQLHLTPFTARGRFATVVEELFRDGVNWGRIVAFFEFGGVMCVESVNREMSPLVDNIALWMTEYLNRHLHTWIQDNGGWDAFVELYGPSMRPLFDFSWLSLKTLLSLALVGACITLGAYLGHK'

def sequence_identity(seq1,seq2):
   c=0
   for i in range (len(seq1)):
       if seq1[i]!=seq2[i]:
           c=+1 
           print('Amino acid residues in position ',i,' are not identical')
   return (1-c/len(seq1))*100

